# Generated by Django 5.0.1 on 2024-01-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('department', models.CharField(choices=[('radiology', 'radiology'), ('neurology', 'neurology'), ('emergency', 'emergency'), ('cardiology', 'cardiology'), ('gynaecology', 'gynaecology')], max_length=50)),
                ('hours', models.PositiveBigIntegerField()),
            ],
        ),
    ]
