# Generated by Django 5.0.1 on 2024-01-31 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='shift',
            field=models.CharField(choices=[('nightshift', 'nightshift'), ('dayshift', 'dayshift')], default=datetime.datetime(2024, 1, 31, 21, 6, 18, 737227, tzinfo=datetime.timezone.utc), max_length=30),
            preserve_default=False,
        ),
    ]
