# Generated by Django 5.0.1 on 2024-02-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0005_duty_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='activity',
            field=models.CharField(choices=[('checkin', 'checkin'), ('checkout', 'checkout')], default='checkin', max_length=30),
        ),
    ]
