# Generated by Django 5.0.1 on 2024-02-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0006_order_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Leave',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='activity',
            field=models.CharField(blank=True, choices=[('checkin', 'checkin'), ('checkout', 'checkout')], default='checkin', max_length=30, null=True),
        ),
    ]
