# Generated by Django 5.0.1 on 2024-02-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0007_leave_alter_order_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='department',
            field=models.CharField(choices=[('radiology', 'radiology'), ('neurology', 'neurology'), ('emergency', 'emergency'), ('cardiology', 'cardiology'), ('gynaecology', 'gynaecology')], default='neurology', max_length=50),
        ),
    ]
