# Generated by Django 5.0.1 on 2024-02-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0008_leave_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='email',
            field=models.EmailField(default='Empty', max_length=254),
        ),
    ]
