# Generated by Django 5.0.1 on 2024-02-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0009_leave_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('department', models.CharField(choices=[('radiology', 'radiology'), ('neurology', 'neurology'), ('emergency', 'emergency'), ('cardiology', 'cardiology'), ('gynaecology', 'gynaecology')], default='neurology', max_length=50)),
                ('email', models.EmailField(default='Empty', max_length=254)),
                ('type', models.CharField(choices=[('sexual harassment', 'sexual harassment'), ('Unfair treatment', 'Unfair treatment'), ('Bullying', 'Bullying'), ('Unhealthy relationships', 'unhealthy relationships'), ('Taken advantage of', 'Taken advantage of'), ('other', 'other')], max_length=40)),
                ('brief_description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
