# Generated by Django 5.0.1 on 2024-02-04 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0010_complains'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('floor', models.PositiveBigIntegerField()),
                ('department', models.CharField(choices=[('radiology', 'radiology'), ('neurology', 'neurology'), ('emergency', 'emergency'), ('cardiology', 'cardiology'), ('gynaecology', 'gynaecology')], max_length=40)),
                ('building', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Ward',
            },
        ),
        migrations.AddField(
            model_name='duty',
            name='ward',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='roster.ward'),
        ),
    ]
