# Generated by Django 5.0.1 on 2024-02-04 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0011_ward_duty_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roster.ward'),
        ),
    ]
